nodeMetadata: {}
jitter:
  workloads: "15s"
  config: "15s"
namespaces:
- name: default
  replicas: 2
  applications:
  - name: tall
    replicas: 1
    instances: 3
  - name: wide
    replicas: 3
    instances: 1
