nodeMetadata: {}
jitter:
  workloads: "15s"
  config: "15s"
namespaces:
- name: default
  replicas: 1
  applications:
  - name: tall
    replicas: 1
    instances: 3
  - name: wide
    replicas: 2
    instances: 1
  - name: external
    replicas: 1
    instances: 100
    podType: external
