apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: pilot-load
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: pilot-load
spec:
  selector:
    app: etcd
  ports:
  - port: 2379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: pilot-load
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: k8s.gcr.io/etcd:3.4.7-0
        args:
        - etcd
        - --data-dir=/var/lib/etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://0.0.0.0:2379
        resources:
          requests:
            memory: 2048Mi
            cpu: 1000m
        volumeMounts:
          - mountPath: /var/lib/etcd
            name: etcd-data
      volumes:
      - emptyDir: {}
        name: etcd-data
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: pilot-load
spec:
  selector:
    app: apiserver
  ports:
  - port: 18090
    name: tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: pilot-load
  labels:
    app: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      name: apiserver
      labels:
        app: apiserver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "18090"
    spec:
      containers:
      - name: apiserver
        image: k8s.gcr.io/kube-apiserver:v1.18.5
        command:
        - kube-apiserver
        - --etcd-servers=http://etcd:2379
        - --disable-admission-plugins="ServiceAccount"
        - --port
        - "18090"
        - --insecure-bind-address
        - 0.0.0.0
        - --service-cluster-ip-range
        - "10.0.0.0/16"
        env:
        - name: KUBE_ADMISSION_CONTROL
          value: ""
        resources:
          requests:
            memory: 2048Mi
            cpu: 1000m
---
apiVersion: v1
kind: Secret
metadata:
  name: pilot-load-multicluster
  namespace: istio-system
  labels:
    istio/multiCluster: "true"
type: Opaque
data:
  pilot-load: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIHNlcnZlcjogaHR0cDovL2FwaXNlcnZlci5waWxvdC1sb2FkOjE4MDkwCiAgbmFtZTogbG9hZApjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogbG9hZAogICAgdXNlcjogZmFrZQogIG5hbWU6IGxvYWQKY3VycmVudC1jb250ZXh0OiBsb2FkCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KdXNlcnM6Ci0gbmFtZTogZmFrZQo=
