# base64 encoded into deploy.yaml with:
# cat kube/kubeconfig.yaml| base64 -w0
apiVersion: v1
clusters:
- cluster:
    server: http://apiserver.pilot-load:18090
  name: load
contexts:
- context:
    cluster: load
    user: fake
  name: load
current-context: load
kind: Config
preferences: {}
users:
- name: fake
