apiVersion: v1
clusters:
- cluster:
    server: http://localhost:18090
  name: load
contexts:
- context:
    cluster: load
    namespace: default-tcikqnku
    user: fake
  name: load
current-context: load
kind: Config
preferences: {}
users:
- name: fake
  user: {}
