# kubeconfig for local portforward with
# kubectl port-forward svc/apiserver -n pilot-load 18090
apiVersion: v1
clusters:
- cluster:
    server: http://localhost:18090
  name: load
contexts:
- context:
    cluster: load
    namespace: workload
    user: ""
  name: load
current-context: load
kind: Config
preferences: {}
users: []
