apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-config
data:
  # Each namespace has 10x100 and 1x1000
  config.yaml: |
    nodeMetadata: {}
    jitter:
      workloads: "1s"
      config: "0"
    namespaces:
    - name: mesh
      replicas: 1
      applications:
      - name: big
        replicas: 10
        instances: 100
      - name: huge
        replicas: 1
        instances: 1000
