apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: pilot-load
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pilot-load
  namespace: pilot-load
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsc-load
  namespace: pilot-load
  labels:
    app: adsc-load
spec:
  selector:
    matchLabels:
      app: adsc-load
  replicas: 1
  template:
    metadata:
      name: adsc-load
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
      labels:
        app: adsc-load
    spec:
      # May take a while to shut down
      serviceAccountName: pilot-load
      terminationGracePeriodSeconds: 10
      containers:
      - name: pilot-load
        image: gcr.io/howardjohn-istio/pilot-load
        imagePullPolicy: Always
        args:
        - "adsc"
        - "--pilot-address=meshconfig.googleapis.com:443"
        - "--count=1"
        resources:
          requests:
            cpu: 100m
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pilot-load
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pilot-load-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pilot-load
subjects:
- kind: ServiceAccount
  name: pilot-load
  namespace: pilot-load