nodeMetadata: {}
jitter:
  workloads: "0s"
  config: "0s"
namespaces:
- name: default
  replicas: 1
  applications:
  - name: wide
    replicas: 10
    instances: 1
    gateways:
      virtualServices: [main]
  - name: gateway
    replicas: 1
    instances: 1
    gateways:
      name: main
      enabled: true
