apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-load
  labels:
    app: pilot-load
spec:
  replicas: 1
  template:
    metadata:
      name: pilot-load
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: pilot-load
    spec:
      restartPolicy: Always
      containers:
      - name: pilot-load
        image: gcr.io/howardjohn-istio/pilot-load
        imagePullPolicy: Always
        args:
          - "--clients"
          - "100"
          - "--pilot-address"
          - "istio-pilot.istio-system:15010"
        resources:
          requests:
            cpu: 40m
            memory: 128Mi
  selector:
    matchLabels:
      app: pilot-load
